"""Cria a tabela municipio para automacao

Revision ID: 233660c7e937
Revises: 9d46bcffc7cb
Create Date: 2025-10-27 19:50:16.541513

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '233660c7e937'
down_revision = '9d46bcffc7cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('municipio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('url_certidao', sa.String(length=300), nullable=False),
    sa.Column('cnpj_field_id', sa.String(length=100), nullable=True),
    sa.Column('by', sa.String(length=20), nullable=True),
    sa.Column('pre_fill_click_id', sa.String(length=100), nullable=True),
    sa.Column('pre_fill_click_by', sa.String(length=20), nullable=True),
    sa.Column('shadow_host_selector', sa.String(length=100), nullable=True),
    sa.Column('inner_input_selector', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('municipio')
    # ### end Alembic commands ###
