"""adiciona status_especial a Certidao no banco

Revision ID: 9d46bcffc7cb
Revises: eca48a272f38
Create Date: 2025-10-27 09:42:19.426010

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d46bcffc7cb'
down_revision = 'eca48a272f38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('certidao', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status_especial', sa.Enum('PENDENTE', name='statusespecial'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('certidao', schema=None) as batch_op:
        batch_op.drop_column('status_especial')

    # ### end Alembic commands ###
