"""Adiciona segundo campo de preenchimento em Municipio

Revision ID: a4a53448d4b5
Revises: 233660c7e937
Create Date: 2025-10-29 19:19:16.603465

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4a53448d4b5'
down_revision = '233660c7e937'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('municipio', schema=None) as batch_op:
        batch_op.add_column(sa.Column('inscricao_field_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('inscricao_field_by', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('municipio', schema=None) as batch_op:
        batch_op.drop_column('inscricao_field_by')
        batch_op.drop_column('inscricao_field_id')

    # ### end Alembic commands ###
