"""Adiciona campo estado na tabela empresa

Revision ID: daa6f22ace0d
Revises: a4a53448d4b5
Create Date: 2026-01-19 15:28:32.261363

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'daa6f22ace0d'
down_revision = 'a4a53448d4b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('empresa', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estado', sa.String(length=2), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('empresa', schema=None) as batch_op:
        batch_op.drop_column('estado')

    # ### end Alembic commands ###
