"""Cria tabelas empresa e certidao

Revision ID: eca48a272f38
Revises: 
Create Date: 2025-10-20 15:50:58.761766

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eca48a272f38'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('empresa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('cnpj', sa.String(length=18), nullable=False),
    sa.Column('cidade', sa.String(length=50), nullable=False),
    sa.Column('inscricao_mobiliaria', sa.String(length=6), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cnpj')
    )
    op.create_table('certidao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('FEDERAL', 'FGTS', 'ESTADUAL', 'MUNICIPAL', 'TRABALHISTA', name='tipocertidao'), nullable=False),
    sa.Column('data_validade', sa.Date(), nullable=True),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('certidao')
    op.drop_table('empresa')
    # ### end Alembic commands ###
